<?php

session_start();

if(!isset($_SESSION['role'])){
    header("Location: ../auth/login.php");
    exit();
}

include("../config/database.php");

$doctors=mysqli_num_rows(mysqli_query($conn,"SELECT * FROM doctors"));
$patients=mysqli_num_rows(mysqli_query($conn,"SELECT * FROM patients"));
$appointments=mysqli_num_rows(mysqli_query($conn,"SELECT * FROM appointments"));
$laboratory=mysqli_num_rows(mysqli_query($conn,"SELECT * FROM laboratory_tests"));
$pharmacy=mysqli_num_rows(mysqli_query($conn,"SELECT * FROM medicines"));
$bills=mysqli_num_rows(mysqli_query($conn,"SELECT * FROM bills"));

$total=mysqli_query($conn,"SELECT SUM(total_amount) AS revenue FROM bills WHERE payment_status='Paid'");
$revenue=mysqli_fetch_assoc($total);

$date=date("d-m-Y");
$time=date("h:i A");

?>

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>Hospital Report</title>

<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">

<style>

*{
margin:0;
padding:0;
box-sizing:border-box;
font-family:Arial,sans-serif;
}

body{
background:#ececec;
padding:40px;
}

.report{

width:900px;
margin:auto;
background:#fff;
padding:40px;
box-shadow:0 0 15px rgba(0,0,0,.2);

}

.header{

display:flex;
justify-content:space-between;
align-items:center;
border-bottom:3px solid #2563eb;
padding-bottom:20px;
margin-bottom:30px;

}

.logo{

font-size:55px;
color:#2563eb;

}

.hospital h1{

color:#2563eb;
font-size:34px;

}

.hospital p{

color:#666;
margin-top:5px;

}

.title{

text-align:center;
margin:30px 0;

}

.title h2{

font-size:30px;
color:#222;

}

.info{

display:flex;
justify-content:space-between;
margin-bottom:30px;

}

.info p{

font-size:17px;
margin:5px 0;

}

table{

width:100%;
border-collapse:collapse;
margin-top:20px;

}

table th{

background:#2563eb;
color:#fff;
padding:14px;

}

table td{

padding:14px;
border:1px solid #ddd;

}

table tr:nth-child(even){

background:#f8f8f8;

}

.total{

margin-top:30px;
background:#2563eb;
color:#fff;
padding:20px;
border-radius:8px;
font-size:24px;
font-weight:bold;
text-align:right;

}

.footer{

margin-top:60px;
display:flex;
justify-content:space-between;

}

.signature{

text-align:center;

}

.signature hr{

width:220px;
margin-bottom:8px;

}

.note{

margin-top:40px;
text-align:center;
color:#666;

}

.print-btn{

margin-top:35px;
text-align:center;

}

.print-btn button{

background:#2563eb;
color:white;
border:none;
padding:14px 30px;
font-size:18px;
border-radius:8px;
cursor:pointer;

}

@media print{

body{

background:white;
padding:0;

}

.report{

box-shadow:none;
width:100%;

}

.print-btn{

display:none;

}

}

</style>

</head>

<body>

<div class="report">

<div class="header">

<div class="logo">

<i class="fa-solid fa-hospital"></i>

</div>

<div class="hospital">

<h1>SUBHAN CARE HOSPITAL</h1>

<p>Hospital Management System</p>

<p>GT Road, Gujrat, Pakistan</p>

</div>

</div>

<div class="title">

<h2>Hospital Summary Report</h2>

</div>

<div class="info">

<div>

<p><strong>Generated By:</strong> Admin</p>

<p><strong>Date:</strong> <?php echo $date; ?></p>

</div>

<div>

<p><strong>Time:</strong> <?php echo $time; ?></p>

<p><strong>Status:</strong> Official Report</p>

</div>

</div>

<table>

<tr>

<th>Module</th>

<th>Total Records</th>

</tr>

<tr>

<td>Total Doctors</td>

<td><?php echo $doctors; ?></td>

</tr>

<tr>

<td>Total Patients</td>

<td><?php echo $patients; ?></td>

</tr>

<tr>

<td>Total Appointments</td>

<td><?php echo $appointments; ?></td>

</tr>

<tr>

<td>Total Laboratory Tests</td>

<td><?php echo $laboratory; ?></td>

</tr>

<tr>

<td>Total Medicines</td>

<td><?php echo $pharmacy; ?></td>

</tr>

<tr>

<td>Total Bills</td>

<td><?php echo $bills; ?></td>

</tr>

</table>

<div class="total">

Total Revenue : Rs.
<?php echo $revenue['revenue'] ?? 0; ?>

</div>

<div class="footer">

<div>

<p><strong>Generated By</strong></p>

<p>Hospital Management System</p>

</div>

<div class="signature">

<hr>

Authorized Signature

</div>

</div>

<div class="note">

This report is automatically generated by the
Subhan Care Hospital Management System.

</div>

<div class="print-btn">

<button onclick="window.print()">

<i class="fa-solid fa-print"></i>

Print Report

</button>

</div>

</div>

</body>

</html>